"""
ClusterBuilderPersona -- Generates compute platform Terraform for
GKE / EKS / AKS / Cloud Run from a deployment intent.
"""

from __future__ import annotations

import logging
import textwrap
from typing import Any

from sevaforge.agents.base_agent import (
    AgentConfig,
    AgentCapability,
    AgentExecutionContext,
)
from sevaforge.agents.personas.base_persona import BasePersona

logger = logging.getLogger(__name__)


class ClusterBuilderPersona(BasePersona):
    """Generates compute platform Terraform (GKE / EKS / AKS / Cloud Run)."""

    persona_name = "cluster-builder"
    owned_paths = ["infrastructure/cluster/"]

    def __init__(self) -> None:
        super().__init__(
            AgentConfig(
                agent_id="persona-cluster-builder",
                name="Cluster Builder Persona",
                description=(
                    "Generates compute platform Terraform for managed "
                    "Kubernetes clusters or serverless runtimes."
                ),
                capabilities=[
                    AgentCapability(
                        name="generate_cluster_terraform",
                        description="Produce Terraform for a managed K8s cluster or serverless runtime",
                    ),
                    AgentCapability(
                        name="generate_node_pools",
                        description="Produce Terraform for cluster node pool configuration",
                    ),
                ],
                tags=["persona", "cluster", "terraform", "kubernetes"],
            )
        )

    # ------------------------------------------------------------------

    async def _produce_artifacts(
        self,
        intent: dict[str, Any],
        params: dict[str, Any],
    ) -> dict[str, Any]:
        artifacts: list[dict[str, Any]] = []
        findings: list[str] = []

        cloud = intent.get("cloud", params.get("cloud", "gcp")).lower()
        project = intent.get("project_id", params.get("project_id", "my-project"))
        region = intent.get("region", params.get("region", "us-central1"))
        cluster_name = intent.get("cluster_name", params.get("cluster_name", "primary"))
        runtime = intent.get("runtime", params.get("runtime", "kubernetes")).lower()

        dispatch = {
            "gcp": self._gke_terraform,
            "aws": self._eks_terraform,
            "azure": self._aks_terraform,
        }

        # Cloud Run special case
        if runtime == "cloudrun":
            tf = self._cloudrun_terraform(project, region, intent)
            artifacts.append(
                self.write_artifact("infrastructure/cluster/main.tf", tf)
            )
            findings.append("Generated Cloud Run service Terraform.")
            return {"artifacts": artifacts, "findings": findings}

        generator = dispatch.get(cloud)
        if generator is None:
            findings.append(
                f"Unsupported cloud '{cloud}'; defaulting to GCP/GKE."
            )
            generator = self._gke_terraform

        tf = generator(project, region, cluster_name, intent)
        artifacts.append(
            self.write_artifact("infrastructure/cluster/main.tf", tf)
        )

        # Node pool config
        node_tf = self._node_pool_terraform(cloud, cluster_name, intent)
        artifacts.append(
            self.write_artifact("infrastructure/cluster/node_pools.tf", node_tf)
        )

        findings.append(
            f"Generated {cloud.upper()} cluster '{cluster_name}' in {region}."
        )

        return {"artifacts": artifacts, "findings": findings}

    # ------------------------------------------------------------------
    # GKE Autopilot
    # ------------------------------------------------------------------

    @staticmethod
    def _gke_terraform(
        project: str, region: str, name: str, intent: dict[str, Any],
    ) -> str:
        network = intent.get("network", "default")
        subnet = intent.get("subnet", "default")
        return textwrap.dedent(f"""\
            # GKE Autopilot cluster -- generated by SevaForge cluster-builder
            resource "google_container_cluster" "{name}" {{
              name     = "{name}"
              project  = "{project}"
              location = "{region}"

              enable_autopilot = true

              network    = "{network}"
              subnetwork = "{subnet}"

              ip_allocation_policy {{
                cluster_secondary_range_name  = "pods"
                services_secondary_range_name = "services"
              }}

              release_channel {{
                channel = "REGULAR"
              }}

              private_cluster_config {{
                enable_private_nodes    = true
                enable_private_endpoint = false
                master_ipv4_cidr_block  = "172.16.0.0/28"
              }}

              master_authorized_networks_config {{
                cidr_blocks {{
                  cidr_block   = "0.0.0.0/0"
                  display_name = "All (restrict in production)"
                }}
              }}

              deletion_protection = false
            }}
        """)

    # ------------------------------------------------------------------
    # EKS (terraform-aws-modules)
    # ------------------------------------------------------------------

    @staticmethod
    def _eks_terraform(
        project: str, region: str, name: str, intent: dict[str, Any],
    ) -> str:
        vpc_id = intent.get("vpc_id", "vpc-REPLACE_ME")
        subnet_ids = intent.get("subnet_ids", ["subnet-REPLACE_1", "subnet-REPLACE_2"])
        subnets = ", ".join(f'"{s}"' for s in subnet_ids)
        return textwrap.dedent(f"""\
            # EKS cluster -- generated by SevaForge cluster-builder
            module "{name}" {{
              source  = "terraform-aws-modules/eks/aws"
              version = "~> 20.0"

              cluster_name    = "{name}"
              cluster_version = "1.30"

              vpc_id     = "{vpc_id}"
              subnet_ids = [{subnets}]

              cluster_endpoint_public_access = true

              eks_managed_node_groups = {{
                default = {{
                  instance_types = ["m6i.large"]
                  min_size       = 1
                  max_size       = 5
                  desired_size   = 2
                }}
              }}

              tags = {{
                Environment = "production"
                ManagedBy   = "sevaforge"
              }}
            }}
        """)

    # ------------------------------------------------------------------
    # AKS
    # ------------------------------------------------------------------

    @staticmethod
    def _aks_terraform(
        project: str, region: str, name: str, intent: dict[str, Any],
    ) -> str:
        rg = intent.get("resource_group", "rg-sevaforge")
        return textwrap.dedent(f"""\
            # AKS cluster -- generated by SevaForge cluster-builder
            resource "azurerm_kubernetes_cluster" "{name}" {{
              name                = "{name}"
              location            = "{region}"
              resource_group_name = "{rg}"
              dns_prefix          = "{name}"

              default_node_pool {{
                name       = "default"
                node_count = 2
                vm_size    = "Standard_D2s_v5"
              }}

              identity {{
                type = "SystemAssigned"
              }}

              network_profile {{
                network_plugin = "azure"
                network_policy = "calico"
              }}

              tags = {{
                Environment = "production"
                ManagedBy   = "sevaforge"
              }}
            }}
        """)

    # ------------------------------------------------------------------
    # Cloud Run
    # ------------------------------------------------------------------

    @staticmethod
    def _cloudrun_terraform(
        project: str, region: str, intent: dict[str, Any],
    ) -> str:
        svc = intent.get("app_name", "myapp")
        image = intent.get("image", f"gcr.io/{project}/{svc}:latest")
        port = int(intent.get("port", 8080))
        return textwrap.dedent(f"""\
            # Cloud Run service -- generated by SevaForge cluster-builder
            resource "google_cloud_run_v2_service" "{svc}" {{
              name     = "{svc}"
              project  = "{project}"
              location = "{region}"

              template {{
                containers {{
                  image = "{image}"
                  ports {{
                    container_port = {port}
                  }}
                  resources {{
                    limits = {{
                      cpu    = "1000m"
                      memory = "512Mi"
                    }}
                  }}
                }}
                scaling {{
                  min_instance_count = 0
                  max_instance_count = 10
                }}
              }}

              traffic {{
                type    = "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
                percent = 100
              }}
            }}

            resource "google_cloud_run_v2_service_iam_member" "{svc}_public" {{
              project  = google_cloud_run_v2_service.{svc}.project
              location = google_cloud_run_v2_service.{svc}.location
              name     = google_cloud_run_v2_service.{svc}.name
              role     = "roles/run.invoker"
              member   = "allUsers"
            }}
        """)

    # ------------------------------------------------------------------
    # Node pools (cloud-dispatched)
    # ------------------------------------------------------------------

    @staticmethod
    def _node_pool_terraform(
        cloud: str, cluster_name: str, intent: dict[str, Any],
    ) -> str:
        machine = intent.get("machine_type", "e2-standard-4")
        min_nodes = int(intent.get("min_nodes", 1))
        max_nodes = int(intent.get("max_nodes", 5))

        if cloud == "gcp":
            return textwrap.dedent(f"""\
                # GKE node pool -- generated by SevaForge cluster-builder
                resource "google_container_node_pool" "{cluster_name}_pool" {{
                  name       = "{cluster_name}-pool"
                  cluster    = google_container_cluster.{cluster_name}.id

                  autoscaling {{
                    min_node_count = {min_nodes}
                    max_node_count = {max_nodes}
                  }}

                  node_config {{
                    machine_type = "{machine}"
                    oauth_scopes = [
                      "https://www.googleapis.com/auth/cloud-platform",
                    ]
                  }}
                }}
            """)

        if cloud == "azure":
            return textwrap.dedent(f"""\
                # AKS extra node pool -- generated by SevaForge cluster-builder
                resource "azurerm_kubernetes_cluster_node_pool" "{cluster_name}_pool" {{
                  name                  = "extra"
                  kubernetes_cluster_id = azurerm_kubernetes_cluster.{cluster_name}.id
                  vm_size               = "Standard_D4s_v5"
                  enable_auto_scaling   = true
                  min_count             = {min_nodes}
                  max_count             = {max_nodes}
                }}
            """)

        # AWS -- handled inline in the EKS module
        return textwrap.dedent(f"""\
            # EKS node pools configured inline in the EKS module.
            # Add additional managed node groups to the module block above.
            # min_size = {min_nodes}, max_size = {max_nodes}
        """)
