"""
CostGuardianPersona -- Generates budget alert Terraform, auto-shutdown
workflows, and teardown workflows from a deployment intent.
"""

from __future__ import annotations

import logging
import textwrap
from typing import Any

from sevaforge.agents.base_agent import (
    AgentConfig,
    AgentCapability,
    AgentExecutionContext,
)
from sevaforge.agents.personas.base_persona import BasePersona

logger = logging.getLogger(__name__)


class CostGuardianPersona(BasePersona):
    """Generates budget alerts, auto-shutdown, and teardown workflows."""

    persona_name = "cost-guardian"
    owned_paths = [".github/workflows/cost-shutdown.yml", "deploy/cost/"]

    def __init__(self) -> None:
        super().__init__(
            AgentConfig(
                agent_id="persona-cost-guardian",
                name="Cost Guardian Persona",
                description=(
                    "Generates budget alert Terraform, scheduled shutdown "
                    "workflows, and full teardown workflows."
                ),
                capabilities=[
                    AgentCapability(
                        name="generate_budget_alerts",
                        description="Produce Terraform for cloud budget alerts",
                    ),
                    AgentCapability(
                        name="generate_shutdown_workflow",
                        description="Produce a cron-based scale-to-zero / restore workflow",
                    ),
                    AgentCapability(
                        name="generate_teardown_workflow",
                        description="Produce a full infrastructure teardown workflow",
                    ),
                ],
                tags=["persona", "cost", "finops", "budget"],
            )
        )

    # ------------------------------------------------------------------

    async def _produce_artifacts(
        self,
        intent: dict[str, Any],
        params: dict[str, Any],
    ) -> dict[str, Any]:
        artifacts: list[dict[str, Any]] = []
        findings: list[str] = []

        cloud = intent.get("cloud", params.get("cloud", "gcp")).lower()
        project = intent.get("project_id", params.get("project_id", "my-project"))
        monthly_budget = int(intent.get("monthly_budget_usd", params.get("monthly_budget_usd", 500)))
        alert_emails = intent.get("alert_emails", params.get("alert_emails", ["team@example.com"]))
        shutdown_cron = intent.get("shutdown_cron", params.get("shutdown_cron", "0 20 * * 1-5"))
        restore_cron = intent.get("restore_cron", params.get("restore_cron", "0 8 * * 1-5"))
        cluster_name = intent.get("cluster_name", params.get("cluster_name", "primary"))
        namespace = intent.get("namespace", params.get("namespace", "default"))

        # -- Budget alerts -----------------------------------------------
        budget_tf = self._generate_budget_terraform(
            cloud, project, monthly_budget, alert_emails,
        )
        artifacts.append(
            self.write_artifact("deploy/cost/budget.tf", budget_tf)
        )
        findings.append(
            f"Budget alert set at ${monthly_budget}/month with thresholds at 50%, 80%, 100%."
        )

        # -- Shutdown workflow -------------------------------------------
        shutdown_wf = self._generate_shutdown_workflow(
            cluster_name, namespace, shutdown_cron, restore_cron,
        )
        artifacts.append(
            self.write_artifact(".github/workflows/cost-shutdown.yml", shutdown_wf)
        )
        findings.append(
            f"Shutdown cron: {shutdown_cron} / restore cron: {restore_cron}."
        )

        # -- Teardown workflow -------------------------------------------
        teardown_wf = self._generate_teardown_workflow(cloud, project)
        artifacts.append(
            self.write_artifact(".github/workflows/teardown.yml", teardown_wf)
        )
        findings.append("Manual teardown workflow generated (requires approval).")

        return {"artifacts": artifacts, "findings": findings}

    # ------------------------------------------------------------------
    # Budget alerts
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_budget_terraform(
        cloud: str,
        project: str,
        budget: int,
        emails: list[str],
    ) -> str:
        if cloud == "aws":
            subscriber_lines = "\n".join(
                f"""\
  subscriber {{
    subscription_type = "EMAIL"
    address           = "{e}"
  }}"""
                for e in emails
            )
            return textwrap.dedent(f"""\
                # AWS Budget -- generated by SevaForge cost-guardian
                resource "aws_budgets_budget" "monthly" {{
                  name         = "sevaforge-monthly"
                  budget_type  = "COST"
                  limit_amount = "{budget}"
                  limit_unit   = "USD"
                  time_unit    = "MONTHLY"

                  notification {{
                    comparison_operator       = "GREATER_THAN"
                    threshold                 = 50
                    threshold_type            = "PERCENTAGE"
                    notification_type         = "ACTUAL"
                {subscriber_lines}
                  }}

                  notification {{
                    comparison_operator       = "GREATER_THAN"
                    threshold                 = 80
                    threshold_type            = "PERCENTAGE"
                    notification_type         = "ACTUAL"
                {subscriber_lines}
                  }}

                  notification {{
                    comparison_operator       = "GREATER_THAN"
                    threshold                 = 100
                    threshold_type            = "PERCENTAGE"
                    notification_type         = "ACTUAL"
                {subscriber_lines}
                  }}
                }}
            """)

        # Default: GCP
        email_list = ", ".join(f'"{e}"' for e in emails)
        return textwrap.dedent(f"""\
            # GCP Budget -- generated by SevaForge cost-guardian
            data "google_billing_account" "account" {{
              display_name = "My Billing Account"
              open         = true
            }}

            resource "google_billing_budget" "monthly" {{
              billing_account = data.google_billing_account.account.id
              display_name    = "sevaforge-monthly-budget"

              budget_filter {{
                projects = ["projects/{project}"]
              }}

              amount {{
                specified_amount {{
                  currency_code = "USD"
                  units         = "{budget}"
                }}
              }}

              threshold_rules {{
                threshold_percent = 0.5
                spend_basis       = "CURRENT_SPEND"
              }}
              threshold_rules {{
                threshold_percent = 0.8
                spend_basis       = "CURRENT_SPEND"
              }}
              threshold_rules {{
                threshold_percent = 1.0
                spend_basis       = "CURRENT_SPEND"
              }}

              all_updates_rule {{
                monitoring_notification_channels = []
                schema_version                   = "1.0"
                pubsub_topic                     = ""
              }}
            }}
        """)

    # ------------------------------------------------------------------
    # Shutdown workflow
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_shutdown_workflow(
        cluster: str,
        namespace: str,
        shutdown_cron: str,
        restore_cron: str,
    ) -> str:
        return textwrap.dedent(f"""\
            # Cost-shutdown workflow -- generated by SevaForge cost-guardian
            name: Cost Shutdown / Restore
            on:
              schedule:
                - cron: "{shutdown_cron}"   # Scale to zero
                - cron: "{restore_cron}"    # Restore
              workflow_dispatch:
                inputs:
                  action:
                    description: "shutdown or restore"
                    required: true
                    type: choice
                    options:
                      - shutdown
                      - restore

            permissions:
              contents: read
              id-token: write

            jobs:
              scale:
                runs-on: ubuntu-latest
                steps:
                  - name: Authenticate
                    uses: google-github-actions/auth@v2
                    with:
                      workload_identity_provider: ${{{{ secrets.WIF_PROVIDER }}}}
                      service_account: ${{{{ secrets.SA_EMAIL }}}}

                  - name: Setup gcloud
                    uses: google-github-actions/setup-gcloud@v2

                  - name: Get credentials
                    run: |
                      gcloud container clusters get-credentials {cluster} \\
                        --region ${{{{ secrets.GCP_REGION }}}} \\
                        --project ${{{{ secrets.GCP_PROJECT }}}}

                  - name: Determine action
                    id: action
                    run: |
                      if [ "${{{{ github.event_name }}}}" = "workflow_dispatch" ]; then
                        echo "mode=${{{{ github.event.inputs.action }}}}" >> "$GITHUB_OUTPUT"
                      elif [ "${{{{ github.event.schedule }}}}" = "{shutdown_cron}" ]; then
                        echo "mode=shutdown" >> "$GITHUB_OUTPUT"
                      else
                        echo "mode=restore" >> "$GITHUB_OUTPUT"
                      fi

                  - name: Shutdown (scale to zero)
                    if: steps.action.outputs.mode == 'shutdown'
                    run: |
                      kubectl -n {namespace} get deployments -o name | \\
                        xargs -I{{}} kubectl -n {namespace} scale {{}} --replicas=0

                  - name: Restore
                    if: steps.action.outputs.mode == 'restore'
                    run: |
                      kubectl -n {namespace} get deployments -o name | \\
                        xargs -I{{}} kubectl -n {namespace} scale {{}} --replicas=2
        """)

    # ------------------------------------------------------------------
    # Teardown workflow
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_teardown_workflow(cloud: str, project: str) -> str:
        return textwrap.dedent(f"""\
            # Teardown workflow -- generated by SevaForge cost-guardian
            name: Full Infrastructure Teardown
            on:
              workflow_dispatch:
                inputs:
                  confirm:
                    description: "Type DESTROY to confirm"
                    required: true

            permissions:
              contents: read
              id-token: write

            jobs:
              teardown:
                runs-on: ubuntu-latest
                if: github.event.inputs.confirm == 'DESTROY'
                environment: production
                steps:
                  - name: Checkout
                    uses: actions/checkout@v4

                  - name: Setup Terraform
                    uses: hashicorp/setup-terraform@v3

                  - name: Authenticate
                    uses: google-github-actions/auth@v2
                    with:
                      workload_identity_provider: ${{{{ secrets.WIF_PROVIDER }}}}
                      service_account: ${{{{ secrets.SA_EMAIL }}}}

                  - name: Terraform Init
                    run: terraform init
                    working-directory: infrastructure/

                  - name: Terraform Destroy
                    run: terraform destroy -auto-approve
                    working-directory: infrastructure/
                    env:
                      TF_VAR_project_id: "{project}"
        """)
