"""
InfraArchitectPersona -- Produces cloud network foundation Terraform
(VPC, subnets, firewalls, providers, backend) from a deployment intent.
"""

from __future__ import annotations

import logging
import textwrap
from typing import Any

from sevaforge.agents.base_agent import (
    AgentConfig,
    AgentCapability,
    AgentExecutionContext,
)
from sevaforge.agents.personas.base_persona import BasePersona

logger = logging.getLogger(__name__)


class InfraArchitectPersona(BasePersona):
    """Produces cloud network foundation Terraform."""

    persona_name = "infra-architect"
    owned_paths = ["infrastructure/network/"]

    def __init__(self) -> None:
        super().__init__(
            AgentConfig(
                agent_id="persona-infra-architect",
                name="Infra Architect Persona",
                description=(
                    "Produces cloud network foundation Terraform -- VPC, "
                    "subnets, firewalls, provider config, and remote backend."
                ),
                capabilities=[
                    AgentCapability(
                        name="generate_network_terraform",
                        description="Produce VPC / subnet / firewall Terraform",
                    ),
                    AgentCapability(
                        name="generate_provider_config",
                        description="Produce provider + backend Terraform files",
                    ),
                ],
                tags=["persona", "infra", "network", "terraform"],
            )
        )

    # ------------------------------------------------------------------

    async def _produce_artifacts(
        self,
        intent: dict[str, Any],
        params: dict[str, Any],
    ) -> dict[str, Any]:
        artifacts: list[dict[str, Any]] = []
        findings: list[str] = []

        cloud = intent.get("cloud", params.get("cloud", "gcp")).lower()
        project = intent.get("project_id", params.get("project_id", "my-project"))
        region = intent.get("region", params.get("region", "us-central1"))
        env = intent.get("environment", params.get("environment", "production"))

        # -- Provider + backend ------------------------------------------
        provider_tf = self._generate_provider(cloud, project, region)
        artifacts.append(
            self.write_artifact("infrastructure/network/provider.tf", provider_tf)
        )

        backend_tf = self._generate_backend(cloud, project, env)
        artifacts.append(
            self.write_artifact("infrastructure/network/backend.tf", backend_tf)
        )

        # -- Network resources -------------------------------------------
        if cloud == "aws":
            net_tf = self._generate_aws_network(region, env)
        else:
            net_tf = self._generate_gcp_network(project, region, env)

        artifacts.append(
            self.write_artifact("infrastructure/network/main.tf", net_tf)
        )

        findings.append(
            f"Generated {cloud.upper()} network foundation for '{env}' in {region}."
        )

        return {"artifacts": artifacts, "findings": findings}

    # ------------------------------------------------------------------
    # Provider / backend
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_provider(cloud: str, project: str, region: str) -> str:
        if cloud == "aws":
            return textwrap.dedent(f"""\
                # AWS provider -- generated by SevaForge infra-architect
                terraform {{
                  required_version = ">= 1.5"
                  required_providers {{
                    aws = {{
                      source  = "hashicorp/aws"
                      version = "~> 5.0"
                    }}
                  }}
                }}

                provider "aws" {{
                  region = "{region}"

                  default_tags {{
                    tags = {{
                      ManagedBy = "sevaforge"
                    }}
                  }}
                }}
            """)

        # Default: GCP
        return textwrap.dedent(f"""\
            # GCP provider -- generated by SevaForge infra-architect
            terraform {{
              required_version = ">= 1.5"
              required_providers {{
                google = {{
                  source  = "hashicorp/google"
                  version = "~> 5.0"
                }}
              }}
            }}

            provider "google" {{
              project = "{project}"
              region  = "{region}"
            }}
        """)

    @staticmethod
    def _generate_backend(cloud: str, project: str, env: str) -> str:
        if cloud == "aws":
            return textwrap.dedent(f"""\
                # Remote backend -- generated by SevaForge infra-architect
                terraform {{
                  backend "s3" {{
                    bucket         = "sevaforge-tfstate-{env}"
                    key            = "network/terraform.tfstate"
                    region         = "us-east-1"
                    encrypt        = true
                    dynamodb_table = "sevaforge-tflock-{env}"
                  }}
                }}
            """)

        return textwrap.dedent(f"""\
            # Remote backend -- generated by SevaForge infra-architect
            terraform {{
              backend "gcs" {{
                bucket = "sevaforge-tfstate-{project}-{env}"
                prefix = "network"
              }}
            }}
        """)

    # ------------------------------------------------------------------
    # GCP network
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_gcp_network(project: str, region: str, env: str) -> str:
        return textwrap.dedent(f"""\
            # GCP VPC + subnets -- generated by SevaForge infra-architect

            resource "google_compute_network" "main" {{
              name                    = "sevaforge-{env}"
              project                 = "{project}"
              auto_create_subnetworks = false
              routing_mode            = "REGIONAL"
            }}

            resource "google_compute_subnetwork" "nodes" {{
              name          = "sevaforge-{env}-nodes"
              project       = "{project}"
              region        = "{region}"
              network       = google_compute_network.main.id
              ip_cidr_range = "10.0.0.0/20"

              secondary_ip_range {{
                range_name    = "pods"
                ip_cidr_range = "10.4.0.0/14"
              }}

              secondary_ip_range {{
                range_name    = "services"
                ip_cidr_range = "10.8.0.0/20"
              }}

              private_ip_google_access = true
            }}

            # Allow internal traffic
            resource "google_compute_firewall" "internal" {{
              name    = "sevaforge-{env}-allow-internal"
              project = "{project}"
              network = google_compute_network.main.name

              allow {{
                protocol = "tcp"
                ports    = ["0-65535"]
              }}
              allow {{
                protocol = "udp"
                ports    = ["0-65535"]
              }}
              allow {{
                protocol = "icmp"
              }}

              source_ranges = ["10.0.0.0/8"]
            }}

            # Allow health checks from GCP load balancer ranges
            resource "google_compute_firewall" "health_checks" {{
              name    = "sevaforge-{env}-allow-health-checks"
              project = "{project}"
              network = google_compute_network.main.name

              allow {{
                protocol = "tcp"
                ports    = ["80", "443", "8080"]
              }}

              source_ranges = [
                "35.191.0.0/16",
                "130.211.0.0/22",
              ]
            }}

            # Outputs
            output "network_name" {{
              value = google_compute_network.main.name
            }}

            output "subnet_name" {{
              value = google_compute_subnetwork.nodes.name
            }}

            output "subnet_cidr" {{
              value = google_compute_subnetwork.nodes.ip_cidr_range
            }}
        """)

    # ------------------------------------------------------------------
    # AWS network
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_aws_network(region: str, env: str) -> str:
        return textwrap.dedent(f"""\
            # AWS VPC + subnets -- generated by SevaForge infra-architect

            resource "aws_vpc" "main" {{
              cidr_block           = "10.0.0.0/16"
              enable_dns_support   = true
              enable_dns_hostnames = true

              tags = {{
                Name = "sevaforge-{env}"
              }}
            }}

            data "aws_availability_zones" "available" {{
              state = "available"
            }}

            resource "aws_subnet" "public_a" {{
              vpc_id                  = aws_vpc.main.id
              cidr_block              = "10.0.1.0/24"
              availability_zone       = data.aws_availability_zones.available.names[0]
              map_public_ip_on_launch = true

              tags = {{
                Name = "sevaforge-{env}-public-a"
              }}
            }}

            resource "aws_subnet" "public_b" {{
              vpc_id                  = aws_vpc.main.id
              cidr_block              = "10.0.2.0/24"
              availability_zone       = data.aws_availability_zones.available.names[1]
              map_public_ip_on_launch = true

              tags = {{
                Name = "sevaforge-{env}-public-b"
              }}
            }}

            resource "aws_internet_gateway" "main" {{
              vpc_id = aws_vpc.main.id

              tags = {{
                Name = "sevaforge-{env}-igw"
              }}
            }}

            resource "aws_route_table" "public" {{
              vpc_id = aws_vpc.main.id

              route {{
                cidr_block = "0.0.0.0/0"
                gateway_id = aws_internet_gateway.main.id
              }}

              tags = {{
                Name = "sevaforge-{env}-public-rt"
              }}
            }}

            resource "aws_route_table_association" "public_a" {{
              subnet_id      = aws_subnet.public_a.id
              route_table_id = aws_route_table.public.id
            }}

            resource "aws_route_table_association" "public_b" {{
              subnet_id      = aws_subnet.public_b.id
              route_table_id = aws_route_table.public.id
            }}

            # Outputs
            output "vpc_id" {{
              value = aws_vpc.main.id
            }}

            output "public_subnet_ids" {{
              value = [
                aws_subnet.public_a.id,
                aws_subnet.public_b.id,
              ]
            }}
        """)
