"""
ObservabilityEngineerPersona -- Generates observability stack configurations:
Prometheus, Grafana dashboards, SLO definitions, and alert rules.
"""

from __future__ import annotations

import json
import logging
import textwrap
from typing import Any

from sevaforge.agents.base_agent import (
    AgentConfig,
    AgentCapability,
    AgentExecutionContext,
)
from sevaforge.agents.personas.base_persona import BasePersona

logger = logging.getLogger(__name__)


class ObservabilityEngineerPersona(BasePersona):
    """Generates Prometheus, Grafana, SLO, and alert configurations."""

    persona_name = "observability-engineer"
    owned_paths = ["deploy/observability/"]

    def __init__(self) -> None:
        super().__init__(
            AgentConfig(
                agent_id="persona-observability-engineer",
                name="Observability Engineer Persona",
                description=(
                    "Generates observability stack configs -- Prometheus, "
                    "Grafana dashboards, SLO definitions, and alert rules."
                ),
                capabilities=[
                    AgentCapability(
                        name="generate_prometheus_config",
                        description="Produce Prometheus scrape config and alert rules",
                    ),
                    AgentCapability(
                        name="generate_slo_config",
                        description="Produce SLO definitions with error budgets",
                    ),
                    AgentCapability(
                        name="generate_grafana_dashboard",
                        description="Produce Grafana dashboard JSON model",
                    ),
                ],
                tags=["persona", "observability", "prometheus", "grafana"],
            )
        )

    # ------------------------------------------------------------------

    async def _produce_artifacts(
        self,
        intent: dict[str, Any],
        params: dict[str, Any],
    ) -> dict[str, Any]:
        artifacts: list[dict[str, Any]] = []
        findings: list[str] = []

        app_name = intent.get("app_name", params.get("app_name", "myapp"))
        port = int(intent.get("port", params.get("port", 8080)))
        namespace = intent.get("namespace", params.get("namespace", "default"))
        stack = intent.get("observability_stack", params.get("observability_stack", "prometheus-grafana")).lower()

        valid_stacks = {"minimal", "prometheus-grafana", "datadog", "cloud-native"}
        if stack not in valid_stacks:
            findings.append(
                f"Unknown stack '{stack}'; defaulting to prometheus-grafana."
            )
            stack = "prometheus-grafana"

        # -- Prometheus config -------------------------------------------
        prom_cfg = self._generate_prometheus_config(app_name, namespace, port)
        artifacts.append(
            self.write_artifact("deploy/observability/prometheus.yml", prom_cfg)
        )

        # -- Alert rules -------------------------------------------------
        alert_rules = self._generate_alert_rules(app_name, namespace)
        artifacts.append(
            self.write_artifact("deploy/observability/alert_rules.yml", alert_rules)
        )

        # -- SLO config --------------------------------------------------
        slo_cfg = self._generate_slo_config(app_name, namespace)
        artifacts.append(
            self.write_artifact("deploy/observability/slo.yml", slo_cfg)
        )

        # -- Grafana dashboard -------------------------------------------
        dashboard = self._generate_grafana_dashboard(app_name, namespace)
        artifacts.append(
            self.write_artifact(
                "deploy/observability/grafana-dashboard.json",
                json.dumps(dashboard, indent=2),
            )
        )

        findings.append(
            f"Observability stack '{stack}' generated for '{app_name}' in {namespace}."
        )

        if stack == "minimal":
            findings.append(
                "Minimal stack: only Prometheus scrape config and basic alerts."
            )

        return {"artifacts": artifacts, "findings": findings}

    # ------------------------------------------------------------------
    # Prometheus
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_prometheus_config(
        app_name: str, namespace: str, port: int,
    ) -> str:
        return textwrap.dedent(f"""\
            # Prometheus config -- generated by SevaForge observability-engineer
            global:
              scrape_interval: 15s
              evaluation_interval: 15s
              external_labels:
                cluster: sevaforge
                namespace: {namespace}

            rule_files:
              - alert_rules.yml

            scrape_configs:
              - job_name: "{app_name}"
                kubernetes_sd_configs:
                  - role: pod
                    namespaces:
                      names:
                        - {namespace}
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_label_app]
                    regex: {app_name}
                    action: keep
                  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
                    target_label: __address__
                    regex: (.+)
                    replacement: ${{1}}:{port}

              - job_name: "kubernetes-pods"
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                    action: keep
                    regex: "true"

              - job_name: "kube-state-metrics"
                static_configs:
                  - targets: ["kube-state-metrics:8080"]
        """)

    # ------------------------------------------------------------------
    # Alert rules
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_alert_rules(app_name: str, namespace: str) -> str:
        return textwrap.dedent(f"""\
            # Alert rules -- generated by SevaForge observability-engineer
            groups:
              - name: {app_name}.availability
                rules:
                  - alert: HighErrorRate
                    expr: |
                      sum(rate(http_requests_total{{namespace="{namespace}",
                        app="{app_name}", code=~"5.."}}[5m]))
                      /
                      sum(rate(http_requests_total{{namespace="{namespace}",
                        app="{app_name}"}}[5m]))
                      > 0.05
                    for: 5m
                    labels:
                      severity: critical
                    annotations:
                      summary: "High error rate on {app_name}"
                      description: "Error rate exceeds 5% for 5 minutes."

                  - alert: HighLatencyP99
                    expr: |
                      histogram_quantile(0.99,
                        sum(rate(http_request_duration_seconds_bucket{{
                          namespace="{namespace}", app="{app_name}"
                        }}[5m])) by (le)
                      ) > 1.0
                    for: 10m
                    labels:
                      severity: warning
                    annotations:
                      summary: "High P99 latency on {app_name}"
                      description: "P99 latency exceeds 1 second for 10 minutes."

              - name: {app_name}.resources
                rules:
                  - alert: PodCrashLooping
                    expr: |
                      rate(kube_pod_container_status_restarts_total{{
                        namespace="{namespace}"
                      }}[15m]) * 60 * 15 > 3
                    for: 5m
                    labels:
                      severity: critical
                    annotations:
                      summary: "Pod crash looping in {namespace}"

                  - alert: HighMemoryUsage
                    expr: |
                      container_memory_working_set_bytes{{
                        namespace="{namespace}"
                      }}
                      /
                      container_spec_memory_limit_bytes{{
                        namespace="{namespace}"
                      }}
                      > 0.9
                    for: 10m
                    labels:
                      severity: warning
                    annotations:
                      summary: "Memory usage above 90% in {namespace}"

                  - alert: PodNotReady
                    expr: |
                      kube_pod_status_ready{{
                        namespace="{namespace}", condition="true"
                      }} == 0
                    for: 15m
                    labels:
                      severity: warning
                    annotations:
                      summary: "Pod not ready for 15 minutes in {namespace}"
        """)

    # ------------------------------------------------------------------
    # SLO config
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_slo_config(app_name: str, namespace: str) -> str:
        return textwrap.dedent(f"""\
            # SLO definitions -- generated by SevaForge observability-engineer
            slos:
              - name: "{app_name}-availability"
                description: "Availability SLO for {app_name}"
                sli:
                  type: availability
                  good_query: |
                    sum(rate(http_requests_total{{namespace="{namespace}",
                      app="{app_name}", code!~"5.."}}[30d]))
                  total_query: |
                    sum(rate(http_requests_total{{namespace="{namespace}",
                      app="{app_name}"}}[30d]))
                objective:
                  target: 0.999
                  window: 30d
                error_budget:
                  burn_rate_alerts:
                    - short_window: 5m
                      long_window: 1h
                      factor: 14.4
                      severity: critical
                    - short_window: 30m
                      long_window: 6h
                      factor: 6.0
                      severity: warning

              - name: "{app_name}-latency"
                description: "Latency SLO for {app_name}"
                sli:
                  type: latency
                  threshold_ms: 500
                  good_query: |
                    sum(rate(http_request_duration_seconds_bucket{{
                      namespace="{namespace}", app="{app_name}", le="0.5"
                    }}[30d]))
                  total_query: |
                    sum(rate(http_request_duration_seconds_count{{
                      namespace="{namespace}", app="{app_name}"
                    }}[30d]))
                objective:
                  target: 0.99
                  window: 30d
        """)

    # ------------------------------------------------------------------
    # Grafana dashboard
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_grafana_dashboard(
        app_name: str, namespace: str,
    ) -> dict[str, Any]:
        return {
            "title": f"{app_name} Overview",
            "uid": f"{app_name}-overview",
            "tags": ["sevaforge", app_name],
            "timezone": "utc",
            "editable": True,
            "refresh": "30s",
            "time": {"from": "now-6h", "to": "now"},
            "panels": [
                {
                    "title": "Request Rate",
                    "type": "timeseries",
                    "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0},
                    "targets": [
                        {
                            "expr": (
                                f'sum(rate(http_requests_total{{'
                                f'namespace="{namespace}", app="{app_name}"'
                                f'}}[5m])) by (code)'
                            ),
                            "legendFormat": "{{code}}",
                        }
                    ],
                },
                {
                    "title": "Latency P50 / P95 / P99",
                    "type": "timeseries",
                    "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0},
                    "targets": [
                        {
                            "expr": (
                                f'histogram_quantile(0.50, sum(rate('
                                f'http_request_duration_seconds_bucket{{'
                                f'namespace="{namespace}", app="{app_name}"'
                                f'}}[5m])) by (le))'
                            ),
                            "legendFormat": "P50",
                        },
                        {
                            "expr": (
                                f'histogram_quantile(0.95, sum(rate('
                                f'http_request_duration_seconds_bucket{{'
                                f'namespace="{namespace}", app="{app_name}"'
                                f'}}[5m])) by (le))'
                            ),
                            "legendFormat": "P95",
                        },
                        {
                            "expr": (
                                f'histogram_quantile(0.99, sum(rate('
                                f'http_request_duration_seconds_bucket{{'
                                f'namespace="{namespace}", app="{app_name}"'
                                f'}}[5m])) by (le))'
                            ),
                            "legendFormat": "P99",
                        },
                    ],
                },
                {
                    "title": "Error Rate %",
                    "type": "gauge",
                    "gridPos": {"h": 8, "w": 6, "x": 0, "y": 8},
                    "targets": [
                        {
                            "expr": (
                                f'sum(rate(http_requests_total{{'
                                f'namespace="{namespace}", app="{app_name}",'
                                f' code=~"5.."}}[5m]))'
                                f' / sum(rate(http_requests_total{{'
                                f'namespace="{namespace}", app="{app_name}"'
                                f'}}[5m])) * 100'
                            ),
                        }
                    ],
                    "fieldConfig": {
                        "defaults": {
                            "thresholds": {
                                "steps": [
                                    {"value": 0, "color": "green"},
                                    {"value": 1, "color": "yellow"},
                                    {"value": 5, "color": "red"},
                                ]
                            },
                            "unit": "percent",
                        }
                    },
                },
                {
                    "title": "Pod Restarts",
                    "type": "stat",
                    "gridPos": {"h": 8, "w": 6, "x": 6, "y": 8},
                    "targets": [
                        {
                            "expr": (
                                f'sum(increase(kube_pod_container_status_restarts_total'
                                f'{{namespace="{namespace}"}}[1h]))'
                            ),
                        }
                    ],
                },
            ],
        }
