"""
SecurityAuditorPersona -- Generates Kubernetes network policies, pod security
configurations, IAM guidance, CI security scanning workflows, and SBOM
generation from a deployment intent.
"""

from __future__ import annotations

import logging
import textwrap
from typing import Any

from sevaforge.agents.base_agent import (
    AgentConfig,
    AgentCapability,
    AgentExecutionContext,
)
from sevaforge.agents.personas.base_persona import BasePersona

logger = logging.getLogger(__name__)


class SecurityAuditorPersona(BasePersona):
    """Generates K8s security policies, CI scans, and SBOM configs."""

    persona_name = "security-auditor"
    owned_paths = ["deploy/security/", ".github/workflows/security-scan.yml"]

    def __init__(self) -> None:
        super().__init__(
            AgentConfig(
                agent_id="persona-security-auditor",
                name="Security Auditor Persona",
                description=(
                    "Generates Kubernetes network policies, pod security "
                    "configs, IAM guidance, CI security scanning workflows, "
                    "and SBOM generation."
                ),
                capabilities=[
                    AgentCapability(
                        name="generate_network_policies",
                        description="Produce K8s NetworkPolicy manifests",
                    ),
                    AgentCapability(
                        name="generate_pod_security",
                        description="Produce pod security standards / admission configs",
                    ),
                    AgentCapability(
                        name="generate_scan_workflow",
                        description="Produce CI security scanning workflow",
                    ),
                ],
                tags=["persona", "security", "network-policy", "sbom"],
            )
        )

    # ------------------------------------------------------------------

    async def _produce_artifacts(
        self,
        intent: dict[str, Any],
        params: dict[str, Any],
    ) -> dict[str, Any]:
        artifacts: list[dict[str, Any]] = []
        findings: list[str] = []

        app_name = intent.get("app_name", params.get("app_name", "myapp"))
        namespace = intent.get("namespace", params.get("namespace", "default"))
        port = int(intent.get("port", params.get("port", 8080)))
        language = intent.get("language", params.get("language", "python")).lower()

        # -- Network policies --------------------------------------------
        netpol = self._generate_network_policies(app_name, namespace, port)
        artifacts.append(
            self.write_artifact("deploy/security/network-policy.yaml", netpol)
        )

        # -- Pod security ------------------------------------------------
        pod_sec = self._generate_pod_security(app_name, namespace)
        artifacts.append(
            self.write_artifact("deploy/security/pod-security.yaml", pod_sec)
        )

        # -- IAM guidance ------------------------------------------------
        iam_doc = self._generate_iam_guidance(intent)
        artifacts.append(
            self.write_artifact("deploy/security/iam-guidance.md", iam_doc)
        )

        # -- CI security scan workflow -----------------------------------
        scan_wf = self._generate_scan_workflow(app_name, language)
        artifacts.append(
            self.write_artifact(
                ".github/workflows/security-scan.yml", scan_wf,
            )
        )

        # -- SBOM --------------------------------------------------------
        sbom_cfg = self._generate_sbom_config(app_name, language)
        artifacts.append(
            self.write_artifact("deploy/security/sbom-config.yml", sbom_cfg)
        )

        if namespace == "default":
            findings.append(
                "WARNING: Deploying to the 'default' namespace is discouraged "
                "for production workloads."
            )

        findings.append(
            f"Security artifacts generated for '{app_name}' ({language})."
        )

        return {"artifacts": artifacts, "findings": findings}

    # ------------------------------------------------------------------
    # Network policies
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_network_policies(
        app_name: str, namespace: str, port: int,
    ) -> str:
        return textwrap.dedent(f"""\
            # K8s NetworkPolicy -- generated by SevaForge security-auditor

            # Default deny all ingress
            apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: default-deny-ingress
              namespace: {namespace}
            spec:
              podSelector: {{}}
              policyTypes:
                - Ingress
            ---
            # Default deny all egress
            apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: default-deny-egress
              namespace: {namespace}
            spec:
              podSelector: {{}}
              policyTypes:
                - Egress
            ---
            # Allow ingress to {app_name} on port {port}
            apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-{app_name}-ingress
              namespace: {namespace}
            spec:
              podSelector:
                matchLabels:
                  app: {app_name}
              policyTypes:
                - Ingress
              ingress:
                - from:
                    - namespaceSelector:
                        matchLabels:
                          name: ingress-nginx
                  ports:
                    - protocol: TCP
                      port: {port}
            ---
            # Allow DNS egress for all pods
            apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-dns-egress
              namespace: {namespace}
            spec:
              podSelector: {{}}
              policyTypes:
                - Egress
              egress:
                - to:
                    - namespaceSelector: {{}}
                  ports:
                    - protocol: UDP
                      port: 53
                    - protocol: TCP
                      port: 53
            ---
            # Allow {app_name} to reach its backends
            apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-{app_name}-egress
              namespace: {namespace}
            spec:
              podSelector:
                matchLabels:
                  app: {app_name}
              policyTypes:
                - Egress
              egress:
                - ports:
                    - protocol: TCP
                      port: 443
                    - protocol: TCP
                      port: 5432
                    - protocol: TCP
                      port: 6379
        """)

    # ------------------------------------------------------------------
    # Pod security
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_pod_security(app_name: str, namespace: str) -> str:
        return textwrap.dedent(f"""\
            # Pod Security Standards -- generated by SevaForge security-auditor

            # Namespace label enforcement (apply via kubectl)
            # kubectl label namespace {namespace} \\
            #   pod-security.kubernetes.io/enforce=restricted \\
            #   pod-security.kubernetes.io/warn=restricted \\
            #   pod-security.kubernetes.io/audit=restricted

            apiVersion: v1
            kind: Namespace
            metadata:
              name: {namespace}
              labels:
                pod-security.kubernetes.io/enforce: restricted
                pod-security.kubernetes.io/warn: restricted
                pod-security.kubernetes.io/audit: restricted
            ---
            # Hardened SecurityContext for {app_name}
            apiVersion: v1
            kind: Pod
            metadata:
              name: {app_name}-security-template
              namespace: {namespace}
              annotations:
                seccomp.security.alpha.kubernetes.io/pod: runtime/default
            spec:
              serviceAccountName: {app_name}
              automountServiceAccountToken: false
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                fsGroup: 1000
                seccompProfile:
                  type: RuntimeDefault
              containers:
                - name: {app_name}
                  securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                      drop:
                        - ALL
                  volumeMounts:
                    - name: tmp
                      mountPath: /tmp
              volumes:
                - name: tmp
                  emptyDir: {{}}
            ---
            # Dedicated ServiceAccount (no default token)
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: {app_name}
              namespace: {namespace}
            automountServiceAccountToken: false
        """)

    # ------------------------------------------------------------------
    # IAM guidance
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_iam_guidance(intent: dict[str, Any]) -> str:
        cloud = intent.get("cloud", "gcp").lower()
        app_name = intent.get("app_name", "myapp")

        if cloud == "aws":
            return textwrap.dedent(f"""\
                # IAM Guidance for {app_name} (AWS)

                Generated by SevaForge security-auditor persona.

                ## Principles
                - Use IAM Roles for Service Accounts (IRSA) instead of static credentials.
                - Follow the principle of least privilege.
                - Use separate roles for CI/CD and runtime workloads.

                ## Recommended Roles
                1. **CI/CD Role** -- used by GitHub Actions via OIDC federation.
                   - `ecr:PushImage`, `ecr:GetAuthorizationToken`
                   - `eks:DescribeCluster`, `eks:UpdateClusterConfig`
                   - Scoped to the specific EKS cluster ARN.

                2. **Runtime Role** -- attached to the pod via IRSA.
                   - Only the permissions the application actually needs.
                   - e.g. `s3:GetObject` on a specific bucket, `sqs:SendMessage` on a specific queue.

                ## Actions
                - [ ] Create OIDC identity provider for GitHub Actions.
                - [ ] Create CI/CD IAM role with trust policy for the GitHub repo.
                - [ ] Create runtime IAM role with minimal permissions.
                - [ ] Associate runtime role with K8s ServiceAccount via IRSA annotation.
            """)

        return textwrap.dedent(f"""\
            # IAM Guidance for {app_name} (GCP)

            Generated by SevaForge security-auditor persona.

            ## Principles
            - Use Workload Identity Federation (WIF) for CI/CD -- no JSON key files.
            - Use GKE Workload Identity for pod-level access -- no node SA sharing.
            - Follow the principle of least privilege.

            ## Recommended Service Accounts
            1. **CI/CD SA** (`{app_name}-ci@PROJECT.iam.gserviceaccount.com`)
               - `roles/artifactregistry.writer` -- push container images
               - `roles/container.developer` -- deploy to GKE
               - Bound to GitHub OIDC via Workload Identity Federation.

            2. **Runtime SA** (`{app_name}-runtime@PROJECT.iam.gserviceaccount.com`)
               - Only the roles the application actually needs.
               - Bound to the K8s ServiceAccount via GKE Workload Identity.

            ## Actions
            - [ ] Create Workload Identity Pool and Provider for GitHub Actions.
            - [ ] Create CI/CD service account and bind to WIF.
            - [ ] Create runtime service account with minimal roles.
            - [ ] Annotate K8s ServiceAccount with `iam.gke.io/gcp-service-account`.
        """)

    # ------------------------------------------------------------------
    # CI security scan workflow
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_scan_workflow(app_name: str, language: str) -> str:
        lang_scanner = {
            "python": "safety check --full-report",
            "node": "npm audit --production",
            "go": "govulncheck ./...",
            "java": "mvn org.owasp:dependency-check-maven:check",
            "ruby": "bundle-audit check",
            "rust": "cargo audit",
        }
        dep_scan_cmd = lang_scanner.get(language, "echo 'No dependency scanner configured'")

        return textwrap.dedent(f"""\
            # Security scan workflow -- generated by SevaForge security-auditor
            name: Security Scan
            on:
              push:
                branches: [main]
              pull_request:
                branches: [main]
              schedule:
                - cron: "0 6 * * 1"   # Weekly Monday 6 AM UTC

            permissions:
              contents: read
              security-events: write

            jobs:
              dependency-scan:
                runs-on: ubuntu-latest
                steps:
                  - uses: actions/checkout@v4

                  - name: Dependency vulnerability scan
                    run: {dep_scan_cmd}

              container-scan:
                runs-on: ubuntu-latest
                needs: dependency-scan
                steps:
                  - uses: actions/checkout@v4

                  - name: Build image
                    run: docker build -t {app_name}:scan .

                  - name: Trivy container scan
                    uses: aquasecurity/trivy-action@master
                    with:
                      image-ref: "{app_name}:scan"
                      format: "sarif"
                      output: "trivy-results.sarif"
                      severity: "CRITICAL,HIGH"

                  - name: Upload SARIF
                    uses: github/codeql-action/upload-sarif@v3
                    with:
                      sarif_file: trivy-results.sarif

              sast:
                runs-on: ubuntu-latest
                steps:
                  - uses: actions/checkout@v4

                  - name: CodeQL analysis
                    uses: github/codeql-action/init@v3
                    with:
                      languages: {language}

                  - name: Autobuild
                    uses: github/codeql-action/autobuild@v3

                  - name: Perform analysis
                    uses: github/codeql-action/analyze@v3

              sbom:
                runs-on: ubuntu-latest
                steps:
                  - uses: actions/checkout@v4

                  - name: Generate SBOM
                    uses: anchore/sbom-action@v0
                    with:
                      format: spdx-json
                      output-file: sbom.spdx.json

                  - name: Upload SBOM
                    uses: actions/upload-artifact@v4
                    with:
                      name: sbom
                      path: sbom.spdx.json
        """)

    # ------------------------------------------------------------------
    # SBOM config
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_sbom_config(app_name: str, language: str) -> str:
        return textwrap.dedent(f"""\
            # SBOM configuration -- generated by SevaForge security-auditor
            sbom:
              format: spdx-json
              tool: syft
              scope:
                - source
                - container-image
              metadata:
                application: {app_name}
                language: {language}
                supplier: "SevaForge Platform"
              output:
                file: sbom.spdx.json
                attest: true
                upload_to_registry: true
              vulnerability_scan:
                enabled: true
                tool: grype
                fail_on: critical
                ignore:
                  - CVE-0000-0000   # Example: known false positive
        """)
