apiVersion: v1
kind: ServiceAccount
metadata:
  name: sevaforge-app
  namespace: sevaforge
  labels:
    app.kubernetes.io/name: sevaforge-app
    app.kubernetes.io/part-of: sevaforge
  annotations:
    iam.gke.io/gcp-service-account: sevaforge-app@sevaforge-prod.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sevaforge-worker
  namespace: sevaforge
  labels:
    app.kubernetes.io/name: sevaforge-worker
    app.kubernetes.io/part-of: sevaforge
  annotations:
    iam.gke.io/gcp-service-account: sevaforge-worker@sevaforge-prod.iam.gserviceaccount.com
