#!/usr/bin/env python3
"""
Documentation Agent - Generates documentation and diagrams.
Mapped to: docs command → diagram_generator_mcp

Reads .forgeflow/inventory.json to produce:
  - docs/architecture.md  — real component Mermaid diagram
  - docs/api.md           — detected API routes per framework
  - docs/CONTRIBUTING.md  — contribution guide (only if missing)
"""
import ast
import json
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .base_agent import BaseAgent


# ---------------------------------------------------------------------------
# Route detection patterns per framework
# ---------------------------------------------------------------------------

# FastAPI / Flask decorator patterns
PYTHON_ROUTE_RE = re.compile(
    r'@(?:app|router|api|blueprint)\.'
    r'(get|post|put|patch|delete|head|options|route)'
    r'\s*\(\s*["\']([^"\']+)["\']',
    re.IGNORECASE,
)

# Django urls.py patterns
DJANGO_PATH_RE = re.compile(
    r'(?:path|re_path|url)\s*\(\s*["\']([^"\']+)["\']',
)
DJANGO_VIEW_RE = re.compile(
    r'(?:path|re_path|url)\s*\([^,]+,\s*([A-Za-z0-9_.]+)',
)

# Express.js patterns
EXPRESS_ROUTE_RE = re.compile(
    r'(?:app|router)\.'
    r'(get|post|put|patch|delete|use|all)'
    r'\s*\(\s*["\`]([^"\'`]+)["\`]',
    re.IGNORECASE,
)

# Go net/http / gin / echo patterns
GO_ROUTE_RE = re.compile(
    r'(?:HandleFunc|GET|POST|PUT|PATCH|DELETE|Handle|Any)\s*\(\s*["\`]([^"\'`]+)["\`]',
)

CONTRIBUTING_TEMPLATE = """\
# Contributing

Thank you for your interest in contributing!

## Getting Started

1. Fork the repository and clone it locally
2. Create a feature branch: `git checkout -b feature/my-feature`
3. Make your changes and add tests where appropriate
4. Run the test suite to make sure everything passes
5. Commit your changes with a clear message
6. Open a Pull Request

## Code Style

- Follow the existing code style in the project
- Run the linter/formatter before submitting (`pre-commit run --all-files`)
- Keep pull requests focused — one feature or fix per PR

## Reporting Issues

Please use GitHub Issues and include:
- A clear description of the problem
- Steps to reproduce
- Expected vs actual behaviour
- Environment details (OS, language version, etc.)

## Pull Request Guidelines

- Reference any related issues in the PR description
- Keep the PR description concise but informative
- Be responsive to review feedback

---
*Generated by ForgeFlow*
"""


class DocumentationAgent(BaseAgent):
    """Agent that generates architecture diagrams, API docs, and contribution guides."""

    def __init__(self):
        super().__init__(
            name="documentation_agent",
            description="Generates architecture diagrams, API route docs, and CONTRIBUTING guide"
        )

    def execute(self, params: Dict[str, Any]) -> Dict[str, Any]:
        repo_path = Path(params.get('path', '.'))
        overwrite = params.get('overwrite', False)
        docs_generated = []

        self.log("Generating documentation...")

        # Ensure docs/ exists
        docs_dir = repo_path / 'docs'
        docs_dir.mkdir(exist_ok=True)

        # Load full inventory (summary + file list)
        inv_data = self._load_inventory(repo_path)
        summary = inv_data.get('summary', {})
        inventory = inv_data.get('inventory', [])
        primary_language = summary.get('primary_language', 'Unknown')
        frameworks = summary.get('frameworks', [])
        entry_points = summary.get('entry_points', [])
        components = summary.get('components', {})
        git_meta = summary.get('git', {})

        self.log(f"Primary language: {primary_language}, frameworks: {frameworks}")

        # 1. Architecture diagram
        docs_generated.append(
            self._generate_architecture_doc(
                docs_dir, repo_path, inventory, summary, overwrite
            )
        )

        # 2. API documentation (real route detection)
        api_result = self._generate_api_doc(
            docs_dir, repo_path, primary_language, frameworks, inventory, overwrite
        )
        if api_result:
            docs_generated.append(api_result)

        # 3. CONTRIBUTING.md (only if missing — never overwrite)
        contrib_result = self._ensure_contributing(repo_path)
        if contrib_result:
            docs_generated.append(contrib_result)

        summary_line = f"Generated {len(docs_generated)} documentation files for {primary_language} project"
        self.log(summary_line)

        return self.create_result(
            status='success',
            summary=summary_line,
            data={
                'docs_dir': str(docs_dir),
                'files': docs_generated,
                'primary_language': primary_language,
                'frameworks': frameworks,
                'inventory_used': len(inventory) > 0,
            },
            findings=[f"{d['type'].upper()}: {d['file']} — {d['status']}" for d in docs_generated]
        )

    # -----------------------------------------------------------------------
    # Inventory loading
    # -----------------------------------------------------------------------

    def _load_inventory(self, repo_path: Path) -> Dict[str, Any]:
        """Load the full inventory dict (summary + file list)."""
        inventory_file = repo_path / '.forgeflow' / 'inventory.json'
        if inventory_file.exists():
            try:
                with open(inventory_file) as f:
                    data = json.load(f)
                if isinstance(data, dict):
                    return data
                # Legacy format: bare list
                if isinstance(data, list):
                    return {'inventory': data, 'summary': {}}
            except Exception as e:
                self.log(f"Could not read inventory.json: {e}", level="warning")
        else:
            self.log("No inventory.json — run discover first for richer docs", level="warning")
        return {'inventory': [], 'summary': {}}

    # -----------------------------------------------------------------------
    # Architecture diagram
    # -----------------------------------------------------------------------

    def _generate_architecture_doc(
        self,
        docs_dir: Path,
        repo_path: Path,
        inventory: List[Dict],
        summary: Dict,
        overwrite: bool,
    ) -> Dict[str, Any]:
        arch_doc = docs_dir / 'architecture.md'
        if arch_doc.exists() and not overwrite:
            return {'file': 'docs/architecture.md', 'type': 'architecture', 'status': 'skipped (already exists)'}

        primary_language = summary.get('primary_language', 'Unknown')
        frameworks = summary.get('frameworks', [])
        git_meta = summary.get('git', {})
        components = summary.get('components', {})  # {component_name: file_count}

        mermaid = self._build_component_diagram(repo_path, inventory, components)

        git_line = ''
        if git_meta.get('is_git_repo'):
            git_line = (
                f"\n> **Branch:** `{git_meta.get('branch', '?')}` · "
                f"**Commits:** {git_meta.get('commit_count', '?')} · "
                f"**Last commit:** {git_meta.get('last_commit', '?')}\n"
            )

        # Build component table from actual inventory
        by_type: Dict[str, int] = defaultdict(int)
        for item in inventory:
            by_type[item.get('component_type', 'other')] += 1

        type_table = "| Component Type | File Count |\n|---|---|\n"
        for ctype, count in sorted(by_type.items(), key=lambda x: -x[1]):
            type_table += f"| {ctype} | {count} |\n"

        framework_section = ""
        if frameworks:
            framework_section = "\n## Detected Frameworks & Tools\n\n"
            framework_section += "\n".join(f"- {f}" for f in sorted(frameworks))
            framework_section += "\n"

        content = f"""# Architecture Overview

*Generated by ForgeFlow on {datetime.now().strftime('%Y-%m-%d %H:%M')}*
{git_line}
**Primary Language:** {primary_language}

## Component Diagram

{mermaid}

## File Distribution

{type_table}
{framework_section}
## Top-Level Components

| Component | Files |
|---|---|
""" + "\n".join(f"| `{name}` | {count} |" for name, count in list(components.items())[:15])

        arch_doc.write_text(content)
        return {'file': 'docs/architecture.md', 'type': 'architecture', 'status': 'generated'}

    def _build_component_diagram(
        self,
        repo_path: Path,
        inventory: List[Dict],
        components: Dict[str, int],
    ) -> str:
        """
        Build a Mermaid diagram based on actual top-level components and their
        detected types rather than generic type-count boxes.
        """
        if not components:
            return "```\nNo components detected — run discover first\n```"

        # Map component_name → dominant type
        comp_types: Dict[str, Dict[str, int]] = defaultdict(lambda: defaultdict(int))
        for item in inventory:
            name = item.get('component_name', 'root')
            ctype = item.get('component_type', 'other')
            comp_types[name][ctype] += 1

        def dominant_type(name):
            if name not in comp_types:
                return 'other'
            return max(comp_types[name], key=comp_types[name].get)

        # Assign Mermaid node shapes by dominant type
        shape_map = {
            'source': ('([', '])'),
            'api': ('([', '])'),
            'test': ('{{', '}}'),
            'config': ('(', ')'),
            'infrastructure': ('[(', ')]'),
            'database': ('[(', ')]'),
            'cicd': ('[/', '/]'),
            'documentation': ('[', ']'),
            'container': ('(', ')'),
            'static': ('[', ']'),
            'other': ('[', ']'),
        }

        lines = ['```mermaid', 'flowchart TD']

        # Subgraph: group by type
        type_groups: Dict[str, List[str]] = defaultdict(list)
        for name in list(components.keys())[:20]:  # cap at 20 components
            dt = dominant_type(name)
            type_groups[dt].append(name)

        node_ids = {}
        for ctype, names in type_groups.items():
            if not names:
                continue
            lines.append(f'    subgraph {ctype.upper()}')
            for name in names:
                node_id = re.sub(r'[^a-zA-Z0-9]', '_', name).upper()
                node_ids[name] = node_id
                open_s, close_s = shape_map.get(ctype, ('[', ']'))
                count = components.get(name, 0)
                lines.append(f'        {node_id}{open_s}"{name} ({count}f)"{close_s}')
            lines.append('    end')

        # Add logical edges based on component names
        edges = self._infer_edges(node_ids, components)
        for src, dst in edges:
            lines.append(f'    {src} --> {dst}')

        lines.append('```')
        return '\n'.join(lines)

    def _infer_edges(
        self, node_ids: Dict[str, str], components: Dict[str, int]
    ) -> List[Tuple[str, str]]:
        """Infer likely relationships from component names."""
        edges = []
        names = list(node_ids.keys())

        edge_rules = [
            # (source pattern, target pattern)
            (['cli', 'cmd', 'api', 'routes', 'controllers', 'handlers'], ['core', 'services', 'lib', 'pkg']),
            (['core', 'services', 'lib', 'pkg', 'internal'],             ['models', 'database', 'schemas', 'db']),
            (['api', 'routes', 'controllers'],                            ['models', 'schemas', 'database']),
            (['tests', 'test', 'spec'],                                   ['src', 'core', 'lib', 'services']),
            (['src', 'app', 'core'],                                      ['config', 'configs']),
        ]

        for sources, targets in edge_rules:
            for src_pat in sources:
                for tgt_pat in targets:
                    src = next((n for n in names if src_pat in n.lower()), None)
                    tgt = next((n for n in names if tgt_pat in n.lower()), None)
                    if src and tgt and src != tgt:
                        pair = (node_ids[src], node_ids[tgt])
                        if pair not in edges:
                            edges.append(pair)
        return edges

    # -----------------------------------------------------------------------
    # API documentation — real route detection
    # -----------------------------------------------------------------------

    def _generate_api_doc(
        self,
        docs_dir: Path,
        repo_path: Path,
        primary_language: str,
        frameworks: List[str],
        inventory: List[Dict],
        overwrite: bool,
    ) -> Optional[Dict[str, Any]]:
        api_doc = docs_dir / 'api.md'
        if api_doc.exists() and not overwrite:
            return {'file': 'docs/api.md', 'type': 'api_docs', 'status': 'skipped (already exists)'}

        routes = []

        if primary_language == 'Python':
            if any(f in frameworks for f in ('FastAPI', 'Flask', 'Starlette')):
                routes = self._detect_python_routes(repo_path, inventory)
            elif 'Django' in frameworks:
                routes = self._detect_django_routes(repo_path, inventory)
        elif primary_language in ('JavaScript', 'TypeScript'):
            if any(f in frameworks for f in ('Express.js', 'Fastify', 'Koa')):
                routes = self._detect_express_routes(repo_path, inventory)
        elif primary_language == 'Go':
            routes = self._detect_go_routes(repo_path, inventory)

        content = self._render_api_doc(primary_language, frameworks, routes)
        api_doc.write_text(content)

        status = f"generated ({len(routes)} routes detected)" if routes else "generated (no routes detected — add manually)"
        return {'file': 'docs/api.md', 'type': 'api_docs', 'status': status}

    def _detect_python_routes(self, repo_path: Path, inventory: List[Dict]) -> List[Dict]:
        routes = []
        py_files = [
            repo_path / item['path'] for item in inventory
            if item['path'].endswith('.py')
            and item.get('component_type') in ('api', 'source', 'other')
        ]
        for py_file in py_files:
            try:
                text = py_file.read_text(errors='ignore')
                for match in PYTHON_ROUTE_RE.finditer(text):
                    method, path = match.group(1).upper(), match.group(2)
                    # Try to find the function name on the next non-decorator line
                    pos = match.end()
                    next_lines = text[pos:pos+200].strip().splitlines()
                    handler = ''
                    for line in next_lines:
                        fn = re.match(r'(?:async\s+)?def\s+(\w+)', line.strip())
                        if fn:
                            handler = fn.group(1)
                            break
                    routes.append({
                        'method': method,
                        'path': path,
                        'handler': handler,
                        'file': str(py_file.relative_to(repo_path)),
                    })
            except Exception:
                pass
        return routes

    def _detect_django_routes(self, repo_path: Path, inventory: List[Dict]) -> List[Dict]:
        routes = []
        url_files = [
            repo_path / item['path'] for item in inventory
            if 'urls' in item['path'] and item['path'].endswith('.py')
        ]
        for url_file in url_files:
            try:
                text = url_file.read_text(errors='ignore')
                paths = DJANGO_PATH_RE.findall(text)
                views = DJANGO_VIEW_RE.findall(text)
                for i, p in enumerate(paths):
                    routes.append({
                        'method': 'GET/POST',
                        'path': f'/{p}',
                        'handler': views[i] if i < len(views) else '',
                        'file': str(url_file.relative_to(repo_path)),
                    })
            except Exception:
                pass
        return routes

    def _detect_express_routes(self, repo_path: Path, inventory: List[Dict]) -> List[Dict]:
        routes = []
        js_files = [
            repo_path / item['path'] for item in inventory
            if item['path'].endswith(('.js', '.ts', '.mjs'))
            and item.get('component_type') in ('api', 'source', 'other')
        ]
        for js_file in js_files:
            try:
                text = js_file.read_text(errors='ignore')
                for match in EXPRESS_ROUTE_RE.finditer(text):
                    method, path = match.group(1).upper(), match.group(2)
                    routes.append({
                        'method': method,
                        'path': path,
                        'handler': '',
                        'file': str(js_file.relative_to(repo_path)),
                    })
            except Exception:
                pass
        return routes

    def _detect_go_routes(self, repo_path: Path, inventory: List[Dict]) -> List[Dict]:
        routes = []
        go_files = [
            repo_path / item['path'] for item in inventory
            if item['path'].endswith('.go')
        ]
        for go_file in go_files:
            try:
                text = go_file.read_text(errors='ignore')
                for match in GO_ROUTE_RE.finditer(text):
                    routes.append({
                        'method': 'ANY',
                        'path': match.group(1),
                        'handler': '',
                        'file': str(go_file.relative_to(repo_path)),
                    })
            except Exception:
                pass
        return routes

    def _render_api_doc(
        self, language: str, frameworks: List[str], routes: List[Dict]
    ) -> str:
        fw_line = ', '.join(frameworks) if frameworks else 'Unknown'
        header = f"""# API Documentation

*Generated by ForgeFlow on {datetime.now().strftime('%Y-%m-%d %H:%M')}*

**Language:** {language} | **Framework(s):** {fw_line}

"""
        if not routes:
            return header + """\
## Endpoints

No routes were auto-detected. This can happen if routes are dynamically registered
or use patterns the scanner doesn't recognise yet. Add your endpoints below:

| Method | Path | Handler | Description |
|--------|------|---------|-------------|
| GET | /api/v1/health | health_check | Health check |

## Authentication

Describe your authentication method here (JWT, API key, OAuth2, etc.).

## Error Responses

| Status | Meaning |
|--------|---------|
| 400 | Bad Request |
| 401 | Unauthorized |
| 404 | Not Found |
| 500 | Internal Server Error |
"""

        # Group routes by file
        by_file: Dict[str, List[Dict]] = defaultdict(list)
        for r in routes:
            by_file[r['file']].append(r)

        content = header + f"## Endpoints ({len(routes)} detected)\n\n"
        for file, file_routes in by_file.items():
            content += f"### `{file}`\n\n"
            content += "| Method | Path | Handler |\n|--------|------|---------|\n"
            for r in file_routes:
                handler = f"`{r['handler']}`" if r['handler'] else '—'
                content += f"| **{r['method']}** | `{r['path']}` | {handler} |\n"
            content += "\n"

        content += """\
## Authentication

Describe your authentication method here (JWT, API key, OAuth2, etc.).

## Error Responses

| Status | Meaning |
|--------|---------|
| 400 | Bad Request |
| 401 | Unauthorized |
| 404 | Not Found |
| 500 | Internal Server Error |
"""
        return content

    # -----------------------------------------------------------------------
    # CONTRIBUTING.md
    # -----------------------------------------------------------------------

    def _ensure_contributing(self, repo_path: Path) -> Optional[Dict[str, Any]]:
        contrib = repo_path / 'CONTRIBUTING.md'
        if contrib.exists():
            return None
        contrib.write_text(CONTRIBUTING_TEMPLATE)
        return {'file': 'CONTRIBUTING.md', 'type': 'contributing', 'status': 'generated'}
