#!/usr/bin/env python3
"""
Documentation Agent - Generates documentation and diagrams.
Mapped to: docs command → diagram_generator_mcp
"""
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List

from .base_agent import BaseAgent


class DocumentationAgent(BaseAgent):
    """Agent that generates documentation and diagrams."""
    
    def __init__(self):
        super().__init__(
            name="documentation_agent",
            description="Generates architecture diagrams, API docs, README"
        )
    
    def execute(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """Generate documentation and diagrams."""
        repo_path = Path(params.get('path', '.'))
        docs_generated = []
        
        self.log("Generating documentation...")
        
        # Create docs directory
        docs_dir = repo_path / 'docs'
        docs_dir.mkdir(exist_ok=True)
        
        # Load inventory if available
        inventory = self._load_inventory(repo_path)
        
        # Generate architecture diagram
        docs_generated.append(self._generate_architecture_doc(docs_dir, inventory))
        
        # Generate API documentation placeholder
        api_result = self._generate_api_doc(docs_dir)
        if api_result:
            docs_generated.append(api_result)
        
        # Update README if needed
        readme_result = self._generate_readme(repo_path)
        if readme_result:
            docs_generated.append(readme_result)
        
        summary = f"Generated {len(docs_generated)} documentation files"
        self.log(summary)
        
        return self.create_result(
            status='success',
            summary=summary,
            data={
                'docs_dir': str(docs_dir),
                'files': docs_generated,
                'inventory_used': len(inventory) > 0
            },
            findings=[f"{d['type']}: {d['file']} - {d['status']}" for d in docs_generated]
        )
    
    def _load_inventory(self, repo_path: Path) -> List[Dict[str, Any]]:
        """Load inventory if available."""
        inventory_file = repo_path / '.forgeflow' / 'inventory.json'
        if inventory_file.exists():
            with open(inventory_file) as f:
                return json.load(f)
        return []
    
    def _generate_architecture_mermaid(self, components: List[Dict[str, Any]]) -> str:
        """Generate Mermaid diagram from components."""
        mermaid = "```mermaid\nflowchart TD\n"
        
        # Group by component type
        by_type = {}
        for comp in components:
            ctype = comp.get('component_type', 'other')
            by_type.setdefault(ctype, []).append(comp)
        
        nodes = []
        for ctype, comps in by_type.items():
            node_id = ctype.upper()
            node_label = f"{ctype} ({len(comps)} files)"
            nodes.append(f"    {node_id}[{node_label}]")
        
        mermaid += "\n".join(nodes)
        
        # Add some connections
        if 'source' in by_type and 'test' in by_type:
            mermaid += "\n    SOURCE --> TEST"
        if 'source' in by_type and 'config' in by_type:
            mermaid += "\n    CONFIG --> SOURCE"
        
        mermaid += "\n```"
        return mermaid
    
    def _generate_architecture_doc(self, docs_dir: Path, inventory: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate architecture documentation."""
        arch_doc = docs_dir / 'architecture.md'
        mermaid_content = self._generate_architecture_mermaid(inventory) if inventory else "No inventory found"
        
        arch_content = f'''# Architecture Overview

Generated by ForgeFlow on {datetime.now().isoformat()}

## Component Diagram

{mermaid_content}

## Components

| Type | Count |
|------|-------|
'''
        
        # Add component counts
        by_type = {}
        for item in inventory:
            ctype = item.get('component_type', 'other')
            by_type[ctype] = by_type.get(ctype, 0) + 1
        for ctype, count in sorted(by_type.items()):
            arch_content += f"| {ctype} | {count} |\n"
        
        arch_doc.write_text(arch_content)
        return {
            'file': 'docs/architecture.md',
            'type': 'architecture',
            'status': 'generated'
        }
    
    def _generate_api_doc(self, docs_dir: Path) -> Dict[str, Any]:
        """Generate API documentation placeholder."""
        api_doc = docs_dir / 'api.md'
        if not api_doc.exists():
            api_content = '''# API Documentation

## Endpoints

*Auto-generate your API documentation here*

## Authentication

Describe authentication methods.

## Examples

```bash
curl -X GET http://localhost:8000/api/v1/health
```
'''
            api_doc.write_text(api_content)
            return {
                'file': 'docs/api.md',
                'type': 'api_docs',
                'status': 'generated'
            }
        return None
    
    def _generate_readme(self, repo_path: Path) -> Dict[str, Any]:
        """Generate README if it doesn't exist."""
        readme_path = repo_path / 'README.md'
        if not readme_path.exists():
            readme_content = '''# Project

> Generated by ForgeFlow

## Quick Start

```bash
docker-compose up -d
```

## Documentation

- [Architecture](docs/architecture.md)
- [API](docs/api.md)

## Development

See [CONTRIBUTING.md](CONTRIBUTING.md) for guidelines.
'''
            readme_path.write_text(readme_content)
            return {
                'file': 'README.md',
                'type': 'readme',
                'status': 'generated'
            }
        return None
